{% set name = "ispyb" %}
{% set version = "5.6.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "9469afab2c638fac66b4502e43224f50514706d2d2a2f1d3d91b0cb6a972c5f8" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://github.com/DiamondLightSource/{{ name }}-api/archive/v{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
    - pytest-runner
  run:
    - python
    - mysql-connector-python

test:
  imports:
    - ispyb
    - ispyb.connector
    - ispyb.connector.mysqlsp
    - ispyb.connector.ws
    - ispyb.interface
    - ispyb.sp
    - ispyb.ws

about:
  home: https://github.com/DiamondLightSource/ispyb-api
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Python package to access ISPyB database
  description: |
    This package provides a python interface to ISPyB.
    It can access the ISPyB database directly or (in
    future versions) run on top of the official ISPyB
    webservices API.
  dev_url: https://github.com/DiamondLightSource/ispyb-api

extra:
  recipe-maintainers:
    - stuartcampbell
    - KarlLevik
    - anthchirp
