{% set name = "ispyb" %}
{% set version = "5.3.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "67476526701388d80194a56ff967431df0de989524cb12f46656e84575a792e6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://github.com/DiamondLightSource/{{ name }}-api/archive/v{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
    - pytest-runner
  run:
    - python
    - enum34  # [py27]
    - mysql-connector-python

test:
  imports:
    - ispyb
    - ispyb.connector
    - ispyb.connector.mysqlsp
    - ispyb.connector.ws
    - ispyb.interface
    - ispyb.sp
    - ispyb.ws

about:
  home: https://github.com/DiamondLightSource/ispyb-api
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Python package to access ISPyB database
  description: |
    This package provides a python interface to ISPyB.
    It can access the ISPyB database directly or (in
    future versions) run on top of the official ISPyB
    webservices API.
  dev_url: https://github.com/DiamondLightSource/ispyb-api

extra:
  recipe-maintainers:
    - stuartcampbell
    - KarlLevik
    - anthchirp
