travis:
  secure:
    BINSTAR_TOKEN: Fo85v23W33sMke98gsu8jQx2xN+tEHJLl5SOFWQn3T4PwtDRbJIwO1EZ2AS1J2wey36icBWvi74aPo5J0eEQ5KM7I5/0KND4IMTWI6f9O/dxT+/9gKEtgUZeIxQ6895OamboNsUomjbxYPZS0qtCb1g8o2HI5C/+krBznCcfK7CVpBZGBgIUMwHEU1o2DAHqYp7G2qiuyDCFtCIPVkO20z1sFUO0U5SjzC+8APljGK1YDUdY3k1nqNRMCzCGSbyKeAZFZua5qoEqUlXe4vq/kKaeoSxzYs4egpoOkUcf6njKZzs9tEdvdy+/P+is+3wxrlpdca64lddQn11I03lC5c6Ec0CmyAQ4GMFIfoBEipnpG7u+JAjQ48Vlift7o+xeXzC6AhCahZLJrLdFVjMN1NwZkJB9rISO5+SvfpJg8oXexv+tV+m7gxMPURkuylf33hP/FigztS/uIxWfSGiJpB0ejFBP7Io+1AKv10Pv8dHwKa+WAAIaam4WzuS4rd/t065Qe9UXiPp0XgQyek41CJT3U4fs2vfMgPTUhZ9hyx1d+z/Fp6ZSFFYy3XSzZ6ZcEPDxNx4L5511F51OgMc+vQaOwNgpWXWBKdRr62seBJ9OSm5rNAu9vbGmrEh1GgIBIlt0ukGNpu8MpV05p87DqNsE9umuH9FfLO2541dpnEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
